Fix TypeScript error in EthereumTransactionPreparer
- Fixed platformData reference to use nft.address instead
- TradeLoop NFT objects don't have platformData property
- Updated to use correct NFT object structure from TradeLoop interface

This resolves the build error:
Property 'platformData' does not exist on type TradeLoop.steps.nfts